name: Static Analysis (strict)

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-strict-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0 mypy==1.6.1
      - name: flake8 (critical rules on src)
        run: |
          # Only run high-signal checks to create a clean baseline
          # E9 = Syntax errors, F63/7/82 = undefined names, F401/F841 = unused imports/variables
          flake8 --isolated src --select=E9,F63,F7,F82 --max-line-length=140
      - name: mypy (focused subset, stricter)
        run: |
          # Focused strict typing on a subset we can reasonably keep green
          mypy --no-incremental --ignore-missing-imports \
               src/llm/local_client.py src/metrics.py \
               src/chunk.py src/query_insights.py \n               src/embed.py src/rerank.py
